spring:
  application:
    name: User Management
  datasource:
    url: jdbc:mysql://localhost:3306/user-management
    username: root
    password: 12345678@Abc
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  secret:
    publicKey: ${PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnSFsxthMSjoyEZpAJkSa77++81gyx2nWQodk8L/wptVZ2AQh+sT2U+WM7hMqykXB/FIRGdU80/ILDvoVVIRkRdgCK9z+sLXbetC8agyW8wAA7gzyvyNY3p30jTtQSE/0LjPDUA5DB8n+TgZXu31jGCtUnGSQGa4LXzqqIvA4l2o2e3mvCx2v89JKA0VWFKPkkX3Wp095OsKswCAVvHCM9bCiKYtbCGl/zz6PBdA5M7hhkeI4uA1En/akHxprnw2eXVhIB1fCIdMRgyAbQ4pt0M/TdZp8YJ1HfM76Wogg4Hk7B2B9cTkINu6+94cMAIsBTuK2TJUhgsWcPD6vFQaNdwIDAQAB}
    privateKey: ${PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCdIWzG2ExKOjIRmkAmRJrvv77zWDLHadZCh2Twv/Cm1VnYBCH6xPZT5YzuEyrKRcH8UhEZ1TzT8gsO+hVUhGRF2AIr3P6wtdt60LxqDJbzAADuDPK/I1jenfSNO1BIT/QuM8NQDkMHyf5OBle7fWMYK1ScZJAZrgtfOqoi8DiXajZ7ea8LHa/z0koDRVYUo+SRfdanT3k6wqzAIBW8cIz1sKIpi1sIaX/PPo8F0DkzuGGR4ji4DUSf9qQfGmufDZ5dWEgHV8Ih0xGDIBtDim3Qz9N1mnxgnUd8zvpaiCDgeTsHYH1xOQg27r73hwwAiwFO4rZMlSGCxZw8Pq8VBo13AgMBAAECggEABFv3lDs3nMvvEdmVrgW/DHkrLTI2qsvNnTOelmC81Snhv9mMDCYTdTqUvOM5ycW3Hu6/M2+LZkpCOKU9VSl6B2piXzgQ5HM+bEnYZLAR0XerpjTee4wff2quD6W7bqM9lHNJuskHmNtb79+ruCfiYKN2BAOjTUGhCVHaPcagtAcBuuJ3a6v+kyCFEcrHbRJvJkzYusjbg+chIEc2RmpBAqZFuKYyzkkmfwQePG3nmR6oLUto6uz2VkkNyvn6Z/vxBKeD2D6qKIBdxgL5ye7oZ+rVzY+fvKOBPmoIbH41rQI7l3cOR1C1KRNM38JfdKcsfFyvpmvsQTiJ0HwtQdqvAQKBgQDSFNKSgULp5LTSk2XeyVJFP328k6vRwcr9oyBtanGko4FHDK4uj/gp3UbrGeGZOx+ANLhm6EBGeTJsFfsN06wKFC5xA1mOBGvKHydGCvtXSmml56nbFZtPTa1ym/xNKJRwdPu1OyouRmvxnePcgjL+t2y1sUaWOGswQAt2xf3FRQKBgQC/ebkDnDchHStDTA3i8AX3/2pTKlp5B4upJ7P7mTEP37NMHAE+edTPRAgAagSV+IkiCU4DgVqJXiXy3DN/g9TXyTDV0hP7z1ONw02l8BBlpAxjDcpNpXuCW9P45imgk8JnG3EUoEmCwDc2ZDAyzhoAC7mIkN71+9q2FMBws389iwKBgFZpZDgI3Uox3cLkCDn8W0/KjuCbaUhNSz7K85Kt/vK2on1kFN1oMK6fqwUXTzllHU7x4IvLqmySe5AD9pE4aQJ4TKYFt7d30BKCf/gKmlnMbOpmAPLxz0FudRK4YK4oK+6Z39Mq8+22372xsUFJeMpXDmsp8RvnNwfQwCZpyDl1AoGBALtlmVLUOAx7rNTfgZPC0ESowNoGUKe1X9W9GuS6SI89pBBwNDN+L25vKdml6TkSFryuGKFLn11kPIXVR72cO9q5eMc8JPzFLARJyhwGuTWQ+eKUI5QcyqWJ1Ar80G7tTk11SRYjze5ey2q7YYTHvCChWQM0rlJXHPYplzJ2KqkDAoGAa5oSQfsKgsu64bNtkvxq3gy6AuXEh5tUWdvkGdymh7iWARsbfY9pLPBzSkBejYKNFkw9Wp1Xzr8W/WFF+Mjhhl36lCfULnTkQAtsX1aahOk4HQOOvaFzbbApiea/XyGYgLPuRlavPIjlwxKwFQgcthiE26vGZ0q20OZAAKBgMEw=}
  redis:
    host: localhost
    port: 6379